global:
  scrape_interval: 15s

scrape_configs:
- job_name: prometheus
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090
    
- job_name: app-flask
  static_configs:
  - targets:
    - flask-app:5000
