{
 "title": "Projetinho",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "taxa media de mudanca",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(requests{location=\"primeira-pagina\"}[1m])",
     "legendFormat": "primeira pagina"
    },
    {
     "expr": "rate(requests{location=\"segunda-pagina\"}[1m])",
     "legendFormat": "segunda pagina"
    }
   ]
  },
  {
   "title": "total requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "requests{location=\"primeira-pagina\"}",
     "legendFormat": "primeira pagina"
    },
    {
     "expr": "requests{location=\"segunda-pagina\"}",
     "legendFormat": "segunda pagina"
    }
   ]
  },
  {
   "title": "aumento de request por status code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(numero_requests_total[1m])) by (status_code)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}